CREATE DATABASE OrderDetail;
USE OrderDetail;
CREATE TABLE EMPLOYEE(
SSN INT PRIMARY KEY,
FName VARCHAR(20),
LName VARCHAR(20),
Zip VARCHAR(15)
);
CREATE TABLE CUSTOMER(
CNumber INT PRIMARY KEY,
FName VARCHAR(20),
LName VARCHAR(20),
ZIPCode VARCHAR(15)
);
CREATE TABLE EMPLOYEE_ORDERS(
OrderNo INT PRIMARY KEY,
Receipt_Date DATE,
Expected_Date DATE,
Actual_Date DATE
);
CREATE TABLE PRODUCT(
PNumber INT PRIMARY KEY,
PName VARCHAR(20),
Price FLOAT,
Quantity int
);
CREATE TABLE ORDERS(
OrderNo INT,
PNumber INT,
Quantity INT,
FOREIGN KEY (OrderNo) REFERENCES EMPLOYEE_ORDERS(OrderNo),
FOREIGN KEY (PNumber) REFERENCES Product(PNumber),
PRIMARY KEY(OrderNo,PNumber)
);
CREATE TABLE CUSTOMER_ORDERS(
EMPLOYEE VARCHAR(20),
CUSTOMER VARCHAR(20),
EMPLOYEE_ORDERS VARCHAR(20),
FOREIGN KEY (Employee) REFERENCES EMPLOYEE(SSN),
FOREIGN KEY (Customer) REFERENCES CUSTOMER(CNumber),
FOREIGN KEY (OrderNo) REFERENCES EMPLOYEE_ORDERS(OrderNo),
PRIMARY KEY(Employee,Customer,OrderNo)
);
 
